build-amd64:
  image: appimagecrafters/appimage-builder
  before_script:
    # update docker
    - apt-get update
    - apt-get install -y git wget
    - pip3 install --upgrade git+https://www.opencode.net/azubieta/appimage-builder.git

    # Nootka build requirements
    - echo 'deb http://archive.neon.kde.org/user/ bionic main' > /etc/apt/sources.list.d/neon.list
    - wget -qO - https://archive.neon.kde.org/public.key | apt-key add -
    - apt-get update
    - apt-get install -y mesa-common-dev libsoundtouch-dev libfftw3-dev libasound2-dev libogg-dev libvorbis-dev libpulse-dev libjack-dev cmake build-essential
    - apt-get install -y qt5-default qtdeclarative5-dev qtquickcontrols2-5-dev qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-dialogs qttranslations5-l10n
  #stage: build
  script:
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DWITH_STATIC_LIB=ON .
    - DESTDIR=AppDir make install
    - mv AppDir/usr/share/metainfo/nootka.appdata.xml AppDir/usr/share/metainfo/sf.net.nootka.appdata.xml
    - export QML_SOURCES_PATHS=$PWD/src/qml
    - export VERSION="$(head -1 $PWD/changes | sed 's/\ /-/g')"-b"$(git rev-list HEAD --count)"
    - appimage-builder --skip-test

  artifacts:
    name:  "Nootka-$(head -1 $PWD/changes | sed 's/\ /-/g')-b$(git rev-list HEAD --count)"
    paths:
      - '*.AppImage*'
